/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    CollabHistoryPanel: typeof import('./src/components/collab/CollabHistoryPanel.vue')['default']
    CollabPanel: typeof import('./src/components/collab/CollabPanel.vue')['default']
    DocumentFilter: typeof import('./src/components/documents/DocumentFilter.vue')['default']
    DocumentTable: typeof import('./src/components/documents/DocumentTable.vue')['default']
    DocumentUpload: typeof import('./src/components/documents/DocumentUpload.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    GlobalSearch: typeof import('./src/components/layout/GlobalSearch.vue')['default']
    LoadingState: typeof import('./src/components/common/LoadingState.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    OnboardingTour: typeof import('./src/components/onboarding/OnboardingTour.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PageSkeleton: typeof import('./src/components/common/PageSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search/SearchBar.vue')['default']
    SearchResults: typeof import('./src/components/search/SearchResults.vue')['default']
    ToastProvider: typeof import('./src/components/common/ToastProvider.vue')['default']
    WikiContent: typeof import('./src/components/wiki/WikiContent.vue')['default']
    WikiEditor: typeof import('./src/components/wiki/WikiEditor.vue')['default']
    WikiSidebar: typeof import('./src/components/wiki/WikiSidebar.vue')['default']
    WikiToc: typeof import('./src/components/wiki/WikiToc.vue')['default']
    WikiVersionHistory: typeof import('./src/components/wiki/WikiVersionHistory.vue')['default']
  }
}
